### PR TITLE
Added use copilot actions

### LINKED ISSUE #5: Add more useCopilotActions and useCopilotChatSuggestions
You can use useCopilotActions and useCopilotChatSuggestions to define various interactions with the calendar. Some interactions that are already defined include the suggestion "counting of today's events,"  which has a corresponding action that counts the number of events in the events state. Think of more creative actions and suggestions and implement them!

If facing any issues, feel free to ask.

### PR DESCRIPTION
**Pull request by AnanteshG**
fixes #5 

I've added the following useCopilotActions :-

- Count total number of events
- Show upcoming events for the next week
- Highlight the busiest days in the month

### CODE REVIEW

**Comment by ChiragAgg5k** [comment]
@AnanteshG thanks for the PR! There are just a few improvements i would like you to make:

1. The upcomingevents suggestion is returning a blank `{}`. You can remove that line entirely and replace it with something like `✅ showing upcoming events`.
    
Screenshot 2024-10-02 at 8 33 44 PM

2. There is repeated info. In the render method, keep the title like `✅ counting number of events`

Screenshot 2024-10-02 at 8 34 33 PM

3. Use the `Button` component for deleting the event. Make the dialog close after deletion of the event.

Screenshot 2024-10-02 at 8 40 02 PM

**Comment by AnanteshG** [comment]
Okay I'll make another PR after implementing the features you've mentioned.

**Comment by ChiragAgg5k** [comment]
@AnanteshG dont make another pr! just commit the new changes and push them. they will automatically reflect here

**Comment by AnanteshG** [comment]
Okay

**Comment by ChiragAgg5k** [comment]
@AnanteshG do let me know if you are facing any issues. would be happy to help

**Comment by AnanteshG** [comment]
No issues! Sorry, got caught up in some work. Will make the PR by tomorrow.

**Comment by ChiragAgg5k** [comment]
@AnanteshG thanks for the pr!

**Pull request merged**
