### PR TITLE
Custom Sign In and Sign Up page using Clerk 

### PR DESCRIPTION
**Pull request by abhi9ab**
Issue #15  
Title:  Add custom sign in page 

This pull request customizes the Sign In and Sign Up pages using the Clerk API. The enhancements include:

* User Authentication: Integrates Clerk API for user authentication on the Sign In and Sign Up pages.
* UI/UX Improvements: Enhances the user interface and user experience for signing in and signing up.
* Error Handling: Adds robust error handling for authentication-related issues.
* Responsive Design: Ensures the pages are responsive and work well on various devices.

Changes

Sign In Page

* Integrated Clerk API for user authentication.
* Improved UI components for a better user experience.
* Added validation and error messages.

Sign Up Page

* Integrated Clerk API for new user registration.
* Enhanced UI elements for a seamless sign-up process.
* Implemented input validation and error handling.

Testing

* Verified that users can successfully sign in and sign up using the new pages.
* Tested the error handling for various scenarios (e.g., incorrect password, existing email).
* Ensured the pages are responsive and work well on different screen sizes.

Screenshots

Large screen

cal buddy sign in

cal buddy sign up

Small screen 

call buddy mobile sign in

### CODE REVIEW

**Comment by ChiragAgg5k** [comment]
Screenshot 2024-10-08 at 9 22 01 PM

@abhi9ab there seems to be some issue

**Comment by ChiragAgg5k** [comment]
Screenshot 2024-10-08 at 9 23 54 PM

**Comment by abhi9ab** [comment]
I'll look into it

**Comment by abhi9ab** [comment]
I think you have to enable the GitHub SSO connection in your clerk dashboard

Screenshot 2024-10-08 230628

**Comment by ChiragAgg5k** [comment]
@abhi9ab Yeah I agree with you. But I wasn't planning on allowing Github authentication, as that indicates the tool/product is developer oriented, whereas cal buddy is meant for everyone. So for now just include Google authentication and email authentication only.

**Comment by abhi9ab** [comment]
Included only Sign in/Sign up with Google and Email authentication feature

Screenshot 2024-10-09 012840

**Comment by ChiragAgg5k** [comment]
@abhi9ab amazing job again! Thanks for contributing

**Pull request merged**
