### PR TITLE
Added Hamburger Menu For Mobile Responsiveness

### PR DESCRIPTION
**Pull request by tanish0912**
Added Hamburger Menu for Mobile Responsiveness

This PR introduces a responsive hamburger menu to improve the navigation experience on smaller screens. The changes include:

1. **Hamburger Menu Button**: 
   - A new hamburger menu button is displayed on smaller screens, replacing the standard navigation links. This enhances the usability and layout of the application on mobile devices.

2. **Mobile Navigation Menu**:
   - When the hamburger menu is clicked, a full-screen overlay menu appears, listing the navigation links in a vertical arrangement. This ensures easy access to all sections of the application without overcrowding the screen.

These changes make the application more user-friendly on mobile devices, ensuring that users have a consistent and intuitive navigation experience regardless of screen size.
Screenshot 2024-10-02 at 11 08 04 PM
Screenshot 2024-10-02 at 11 08 17 PM

---
PS : Fixed the previous build issue of pnpm lock file.

### CODE REVIEW

**Comment by ChiragAgg5k** [comment]
@tanish0912 thanks for the pr! everything looks good. just a small adjustment. can you add smooth scrolling to the links just like the original links had?

**Comment by tanish0912** [comment]
On it, will raise the pr soon.

**Comment by ChiragAgg5k** [comment]
@tanish0912 do let me know if u are facing any issues. would be happy to help

**Comment by tanish0912** [comment]
Have solved the issue will be raising the pr by tonight!

**Comment by tanish0912** [comment]
I have added the commit please check.

**Comment by tanish0912** [comment]
I have committed the changes please check.

**Comment by ChiragAgg5k** [comment]
@tanish0912 thanks for your contribution!

**Comment by tanish0912** [comment]
Your welcome!

**Pull request merged**
