### PR TITLE
Resolved the conflict

### PR DESCRIPTION
**Pull request by tanish0912**
I have resolved the conflict and made the footer cleaner and minimal. 
Please check and do let me know if anything else is needed.
Thanks, Happy to Help!

### CODE REVIEW

**Comment by ChiragAgg5k** [comment]
@tanish0912 thanks for the commit. i appreciate the work, but i think the footer looked better in the text and links being in far ends configuration.

as for the hover effect, can you make it better by making it animated?  something like this - https://www.creative-tim.com/twcomponents/component/link-underline-animation

make sure this animation is followed on all text having underline hover effect.

thanks

**Comment by tanish0912** [comment]
Can you please elaborate what you mean by
"but i think the footer looked better in the text and links being in far
ends configuration."
Do you want the footer to look like before?

**Comment by ChiragAgg5k** [comment]
Yes @abhi9ab, you can revert the design back to original, and incorporate the custom hover animation change only

**Comment by tanish0912** [comment]
Okay will do that and raise the pr.

**Pull request closed without merging**
